<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <!-- Prevent build from depending on analyzer assets that may be missing in some environments -->
    <DisableImplicitRoslynAnalyzers>true</DisableImplicitRoslynAnalyzers>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
		<PackageReference Include="Mediator.SourceGenerator" Version="2.1.7">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentValidation" Version="12.1.1" />

		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2">
		  <ExcludeAssets>analyzers</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2">
		  <ExcludeAssets>analyzers</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2">
		  <ExcludeAssets>analyzers</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2">
		  <ExcludeAssets>analyzers</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Account\Identity\Requests\" />
	  <Folder Include="Account\Requests\" />
	</ItemGroup>

</Project>
